### ISSUE TITLE
Are the code blocks supposed to be interactive?

### ISSUE THREAD

**Issue by daaronr** [mca91/EconometricsWithR#17]
![image](https://user-images.githubusercontent.com/8229168/61406018-f3e54c00-a8d2-11e9-97aa-cb46c3f8da39.png)

I can't get these to do anything. (Chrome, Firefox browers on Mac).  Could these be made interactive via 'shiny'?

**Comment by mca91** [comment]
No, these blocks aren't interactive. They are generated using code chunks in bookdown and simply show markedup code; see, e.g., the corresponding [chapter](https://bookdown.org/yihui/rmarkdown/r-code.html) in the rmarkdown book.

In principle, the chunks could be replaced by shiny apps which, however, would require a background R session.

**Comment by daaronr** [comment]
Thank you. I see there are Shiny apps elsewhere in the text.
