### ISSUE TITLE
Website Sidebar links for exercises all direct to section 2.3

### ISSUE THREAD

**Issue by KrishnaTO** [mca91/EconometricsWithR#20]
Sections 3.8, 4.6, etc (exercises pages) link to section 2.3

Next section selection via 3.7 -> 3.8 is working fine. 

Great site, cheers.

**Comment by mca91** [comment]
Thank you, this was due to an update to the bookdown package. Has been [fixed](https://github.com/mca91/EconometricsWithR/commit/56dc45fa2c1293eebad25d25ffeb18e75aa82e0a)!
