### ISSUE TITLE
Notification of license violation

### ISSUE THREAD

**Issue by ttimbers** [mca91/EconometricsWithR#23]
@mca91 @martinschmelzer - just wanted to let you know that it looks like your license for this book is being violated by @dsciencelabs:

- https://github.com/dsciencelabs/Econometrics-With-R/blob/fb5d71e724eafc7db90760e0df227f944babfb81/index.Rmd#L4
- more here: https://github.com/dsciencelabs/Econometrics-With-R/search?q=Bakti+Siregar

This happened to us as well (see report here: https://github.com/dsciencelabs/introduction-to-datascience1/issues/1) and so I thought I would check to see if it was happening to anyone else, and I came across your book.

**Comment by mca91** [comment]
Hi Tiffany,

that's just outrageous. Thanks for bringing this to our attention! Also going to file a query for immediate removal or compliance to the CC license.

Best,
Martin

**Comment by mca91** [comment]
@ttimbers Seems he took the repositories down. However, I stumbled upon [this version of your data science book at book down.org](https://bookdown.org/BaktiSiregar/data-science-for-beginners/).

**Comment by ttimbers** [comment]
Thanks - but that one is not ours... Not sure if it belongs to someone else however. They took ours down today as well thankfully.
