### ISSUE TITLE
Math input error

### ISSUE THREAD

**Issue by davidbroska** [mca91/EconometricsWithR#29]
Hey, I just wanted to flag that there is a math input error in [3.1 Estimation of the Population Mean](https://www.econometrics-with-r.org/3.1-estimation-of-the-population-mean.html).

![image](https://user-images.githubusercontent.com/19816335/226697208-ac360132-8119-4313-9659-43ad1ff5968d.png)

**Comment by mca91** [comment]
Hi David,

thanks for the hint! I've just fixed the issue an pushed an updated version in 2a5f122578ebb7c7b3fc5e53372496cf37a3ba5e.
