### ISSUE TITLE
Domain offline? econometrics-with-r.org

### ISSUE THREAD

**Issue by beatrizmilz** [mca91/EconometricsWithR#44]
Hi! I'm trying to access the website, but it's showing this error:

![imagem](https://github.com/user-attachments/assets/7597b30f-e390-4454-b4dd-6beacba12021)

Maybe the domain is offline?

Is there any other link that is available?

Thank you!

**Comment by mca91** [comment]
Hi,

the website is hosted @ github Pages, maybe there was an outage? Works fine for me (accessing from Spain).

**Comment by beatrizmilz** [comment]
Hi! Thank you for responding @mca91 . 

I'm not sure why that happened. Yesterday and today I tried to access, and it worked! 
I'm accessing from Brazil.
Since it's working, I'm closing this issue. Sorry!!
